config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'users#main'

  get 'users' => 'users#main'
  
  post 'pets/:id' => 'users#follow', as: :follow
  
  #####
  #PETS
  #####
  get 'pets' => 'pets#main'
  #create profile
  get 'pets/new' => 'pets#new', as: :new_pet #retrieve form
  post 'pets' => 'pets#create' #post
  #display profile
  get 'pets/:id' => 'pets#show', as: :pet
  #edit profile
  get 'pets/:id/edit' => 'pets#edit', as: :edit_pet
  patch 'pets/:id' => 'pets#update', as: :update_pet
  #delete profile
  delete 'pets/:id' => 'pets#delete'

  #######
  #ALBUMS
  #######
  get 'pets/:pet_id/albums' => 'albums#main', as: :albums

  get 'pets/:pet_id/albums/new' => 'albums#new', as: :new_album
  post 'pets/:pet_id/albums' => 'albums#create', as: :create_album

  get 'pets/:pet_id/albums/:id' => 'albums#show', as: :album

  get 'pets/:pet_id/albums/:id/edit' => 'albums#edit', as: :edit_album
  patch 'pets/:pet_id/albums/:id' => 'albums#update', as: :update_album

  delete 'pets/:pet_id/albums/:id' => 'albums#delete'

  #######
  #PHOTOS
  #######
  get 'pets/:pet_id/albums/:album_id/photos/' => 'photos#main', as: :photos

  get 'pets/:pet_id/albums/:album_id/photos/new' => 'photos#new', as: :new_photo
  post 'pets/:pet_id/albums/:album_id/photos' => 'photos#create', as: :create_photo

  get 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#show', as: :photo

  get 'pets/:pet_id/albums/:album_id/photos/:id/edit' => 'photos#edit', as: :edit_photo
  patch 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#update', as: :update_photo

  delete 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#delete'

  ##########
  #FOLLOWING
  ##########
  post 'pets/:id/follow' => 'pets#follow', as: :follow_pet
  delete 'pets/:id/unfollow' => 'pets#unfollow', as: :unfollow_pet

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :pets, dependent: :destroy

	has_many :followers, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def main

    #sort pets with search
    if params[:search]
      @pets = Pet.search(params[:search])
    else
    	@pets = Pet.all
    end
    # @pets = Pet.search(params[:search])
  	@photos = Photo.all
  	@pet_array = []
    @pet_indexes = []
  	@photo_array = []
    @following_pets = []
    @following_photos = []

    #collect all pets being followed
    if user_signed_in?
      followings = Follower.where(user_id: current_user.id)
      followings.each do |follow|
        pet = Pet.where(id: follow.pet_id)
        @following_pets << pet[0]
        album = Album.where(pet_id: pet[0].id)
        photo = Photo.where(album_id: album[0].id)
        @following_photos << photo[0]
      end
    end

    # @pets.each do |pet|
    #   test = true
    #   @following_pets.each do |following|
    #     if following.id == pet.id
    #       test = false
    #     end
    #   end
    #   if test
    #     albums = Album.where(pet_id: pet.id)
    #     if albums.length != 0
    #       photos = Photo.where(album_id: albums[0].id)
    #       if photos.length != 0
    #         @photo_array << photos[0]
    #         @pet_array << pet
    #       end
    #     end
    #   end
    # end


    # # while loop to randomize pets shown in main page
    # while @pet_array.length < 50 and @pet_array.length < (@pets.length-@following_pets.length) do
    #   @test = true
    #   @num = rand(@pets.length).to_i

    #   @pet_indexes.each do |x|
    #     if x == @num
    #       @test = false
    #     end
    #   end

    #   @following_pets.each do |pet|
    #     if pet.id == @pets[@num].id
    #       @test = false
    #     end
    #   end

    #   if @test
    #     #find album belonging to pet
    #     @album = Album.where(pet_id: @pets[@num].id)
    #     if @album.length != 0
    #       #find one photo
    #         photos = Photo.where(album_id: @album[0].id)
    #         if photos.length != 0
    #         @photo_array << Photo.where(album_id: @album[0].id)[0]
    #         @pet_array << @pets[@num]
    #         @pet_indexes << @num
    #         end
    #     end
    #   end
    # end

    # sort out pets without albums
    while @pet_array.length < 50 and @pet_array.length < @pets.length do
      @pets.each do |pet|
        albums = Album.where(pet_id: pet.id)
        if albums.length > 0
          albums.each do |album|
            photos = Photo.where(album_id: album.id)
            if photos.length > 0
              @photo_array << photos[0]
              @pet_array << pet
            end
          end
        end
      end
    end

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/main.html.erb
<% form_tag users_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% if user_signed_in? %>
	<% if @following_pets.length > 0 %>
		<div id="wrapper">
				
				<h1>Following</h1>
			
			<div id="columns">
				<% @following_pets.length.times do |x| %>
					<div class="pin">
						<%= link_to "", unfollow_pet_path(@following_pets[x].id), class:"fa fa-heart followed", :method => :delete %>
						<%= image_tag @following_photos[x].avatar_url(:thumb).to_s %><br>
						<%= link_to @following_pets[x].name, pet_path(@following_pets[x].id) %>
						<p><%="#{@following_pets[x].gender} #{@following_pets[x].breed}"%></p>
						<p><%=@following_pets[x].bio%></p>
					</div>
				<%end%>
			</div>
		</div>
	<% end %>
<% end %>

<div id="wrapper">
	<h1>Cool Pets</h1>


	<div id="columns">	
		<% (@pet_array.length).times do |x| %>
			<div class="pin">
				<%= link_to "", follow_pet_path(@pet_array[x].id), class:"fa fa-heart-o follow", :method => :post %>
				<%= image_tag @photo_array[x].avatar_url(:thumb).to_s %><br>
				<%= link_to @pet_array[x].name, pet_path(@pet_array[x].id) %>
				<p><%="#{@pet_array[x].gender} #{@pet_array[x].breed}"%></p>
				<p><%=@pet_array[x].bio%></p>
			</div>
		<% end %>		
	</div>
</div>