config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'users#main'

  get 'users' => 'users#main'
  
  post 'pets/:id' => 'users#follow', as: :follow
  
  #####
  #PETS
  #####
  get 'pets' => 'pets#main'
  #create profile
  get 'pets/new' => 'pets#new', as: :new_pet #retrieve form
  post 'pets' => 'pets#create' #post
  #display profile
  get 'pets/:id' => 'pets#show', as: :pet
  #edit profile
  get 'pets/:id/edit' => 'pets#edit', as: :edit_pet
  patch 'pets/:id' => 'pets#update', as: :update_pet
  #delete profile
  delete 'pets/:id' => 'pets#delete'

  #######
  #ALBUMS
  #######
  get 'pets/:pet_id/albums' => 'albums#main', as: :albums

  get 'pets/:pet_id/albums/new' => 'albums#new', as: :new_album
  post 'pets/:pet_id/albums' => 'albums#create', as: :create_album

  get 'pets/:pet_id/albums/:id' => 'albums#show', as: :album

  get 'pets/:pet_id/albums/:id/edit' => 'albums#edit', as: :edit_album
  patch 'pets/:pet_id/albums/:id' => 'albums#update', as: :update_album

  delete 'pets/:pet_id/albums/:id' => 'albums#delete'

  #######
  #PHOTOS
  #######
  get 'pets/:pet_id/albums/:album_id/photos/' => 'photos#main', as: :photos

  get 'pets/:pet_id/albums/:album_id/photos/new' => 'photos#new', as: :new_photo
  post 'pets/:pet_id/albums/:album_id/photos' => 'photos#create', as: :create_photo

  get 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#show', as: :photo

  get 'pets/:pet_id/albums/:album_id/photos/:id/edit' => 'photos#edit', as: :edit_photo
  patch 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#update', as: :update_photo

  delete 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#delete'

  ##########
  #FOLLOWING
  ##########
  post 'pets/:id/follow' => 'pets#follow', as: :follow_pet
  delete 'pets/:id/unfollow' => 'pets#unfollow', as: :unfollow_pet

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
	belongs_to :pet
	has_many :photos, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def main
    @albums = Album.where(pet_id: set_pet_id)
    @pet_id = set_pet_id
    @pet = Pet.where(id: @pet_id)
  end

  def new
  	@album = Album.new
    @pet_id = set_pet_id
  end

  def create
  	@album = Album.new(album_params)
    if @album.save
      redirect_to new_photo_path(@album.pet_id, @album.id)
    else
      render :new
    end
  end

  def show
    @album = set_album
    @pet_id = set_pet_id
    @pet = Pet.where(id: @pet_id)
    @photos = Photo.where(album_id: @album.id)
    @user = current_user
  end

  def edit
    @album = set_album
  end

  def update
    @album = set_album
    if @album.update_attributes(album_params)
      redirect_to album_path @album.pet_id, @album.id
    else
      render :edit
    end
  end

  def delete
    @album = set_album
    @pet_id = @album.pet_id
    @album.destroy
    redirect_to pet_path(@pet_id)
  end

  private

  def set_album
    Album.find(params[:id])
  end

  def set_pet_id
    params[:pet_id]
  end

  def album_params
  	params.require(:album).permit(:title, :description, :pet_id)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album, url: create_album_path) do |f| %>

  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Title" %><br>
    <%= f.text_field :title, autofocus: true, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_field :description, autocomplete: "off" %>
  </div>

  <!-- hidden field to add relationship between album and pet -->
  <div class="field">
    <%= f.hidden_field :pet_id, :value => @pet_id %>
  </div>

  <div class="actions">
    <%= f.submit "Save" %>
  </div>

<% end %>

app/views/albums/edit.html.erb
<%= form_for(@album, url: update_album_path) do |f| %>

  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_box form-horizontal">
    <h1>Edit Album</h1>
    <div class="form-group first">
      <%= f.label "Title", class:"col-md-3 lower"%>
      <div class="col-md-9">      
        <%= f.text_field :title, class:"form-control", autofocus: true, autocomplete: "off" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "Description", class:"col-md-3 lower" %>
      <div class="col-md-9">      
        <%= f.text_field :description, class:"form-control", autocomplete: "off" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "Save", class: "button"%>
    </div>
  </div>

<% end %>

app/views/albums/main.html.erb
<div class="container-fluid box">
	<h1>Albums</h1>
	<div class="pet spacer">
		<%= link_to "Create Album", new_album_path(@pet_id) %> <br>
		<%= link_to "Back to #{@pet.name}", pet_path(@pet_id) %>
	</div>
	<div class="row last">
		<% @albums.each do |album| %>			
			<div class="col-xs-4 col-sm-4 col-md-4 pet">
				<%= link_to album.title, album_path(album.id) %>
			</div>
		<% end %>
	</div>
</div>

app/views/albums/new.html.erb
<%= form_for(@album, url: create_album_path) do |f| %>

  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_box form-horizontal">
    <h1>New Album</h1>
    <div class="form-group first">
      <%= f.label "Title", class:"col-md-3 lower"%>
      <div class="col-md-9">      
        <%= f.text_field :title, class:"form-control", placeholder: "Title", autofocus: true, autocomplete: "off" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "Description", class:"col-md-3 lower" %>
      <div class="col-md-9">      
        <%= f.text_field :description, class:"form-control", placeholder: "Description", autocomplete: "off" %>
      </div>
    </div>

    <!-- hidden field to add relationship between pet and current user -->
    <%= f.hidden_field :pet_id, :value => @pet_id %>

    <div class="form-group">
      <%= f.submit "Save", class: "button"%>
    </div>
  </div>

<% end %>

  

app/views/albums/show.html.erb
<div class="box" id="wrapper">
	<header>
		<h1><%= "#{@album.title} Album" %></h1>
		<p><%= @album.description %></p>
	</header>
	<div class="pet last">
		<% if @pet[0].user_id == current_user.id %>
			<%= link_to "Edit", edit_album_path(@pet_id, @album.id) %> &nbsp;&nbsp;
			<%= link_to "Delete", album_path(@pet_id, @album.id), :method => :delete %> &nbsp;&nbsp;
			<%= link_to "Add Photo", new_photo_path(@pet_id, @album.id) %><br>
		<% end %>

		<%= link_to "Back to #{@album.pet.name}'s Profile", pet_path(@pet_id) %>
		<!-- 
		<%= link_to "All Albums", albums_path(@album.pet_id) %><br>
		 -->
	</div>
	<!-- display photos -->
	<h2 class="page">Photos</h2>
	<div id="columns">
		<% @photos.each do |photo| %>
			<div class="pin">
			  <%= image_tag photo.avatar_url(:thumb).to_s %>
				<%= link_to photo.description, photo_path(@pet_id, @album.id, photo.id) %>
			</div>
		<% end %>
	</div>
</div>