config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'users#main'

  get 'users' => 'users#main'
  
  post 'pets/:id' => 'users#follow', as: :follow
  
  #####
  #PETS
  #####
  get 'pets' => 'pets#main'
  #create profile
  get 'pets/new' => 'pets#new', as: :new_pet #retrieve form
  post 'pets' => 'pets#create' #post
  #display profile
  get 'pets/:id' => 'pets#show', as: :pet
  #edit profile
  get 'pets/:id/edit' => 'pets#edit', as: :edit_pet
  patch 'pets/:id' => 'pets#update', as: :update_pet
  #delete profile
  delete 'pets/:id' => 'pets#delete'

  #######
  #ALBUMS
  #######
  get 'pets/:pet_id/albums' => 'albums#main', as: :albums

  get 'pets/:pet_id/albums/new' => 'albums#new', as: :new_album
  post 'pets/:pet_id/albums' => 'albums#create', as: :create_album

  get 'pets/:pet_id/albums/:id' => 'albums#show', as: :album

  get 'pets/:pet_id/albums/:id/edit' => 'albums#edit', as: :edit_album
  patch 'pets/:pet_id/albums/:id' => 'albums#update', as: :update_album

  delete 'pets/:pet_id/albums/:id' => 'albums#delete'

  #######
  #PHOTOS
  #######
  get 'pets/:pet_id/albums/:album_id/photos/' => 'photos#main', as: :photos

  get 'pets/:pet_id/albums/:album_id/photos/new' => 'photos#new', as: :new_photo
  post 'pets/:pet_id/albums/:album_id/photos' => 'photos#create', as: :create_photo

  get 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#show', as: :photo

  get 'pets/:pet_id/albums/:album_id/photos/:id/edit' => 'photos#edit', as: :edit_photo
  patch 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#update', as: :update_photo

  delete 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#delete'

  ##########
  #FOLLOWING
  ##########
  post 'pets/:id/follow' => 'pets#follow', as: :follow_pet
  delete 'pets/:id/unfollow' => 'pets#unfollow', as: :unfollow_pet

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :album
	mount_uploader :avatar, AvatarUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def main
    @photos = Photo.where(album_id: set_album_id)
  end

  def new
  	@photo = Photo.new
    @album_id = set_album_id
  end

  def create
  	@photo = Photo.new(photo_params)
    @album_id = set_album_id
    @pet_id = set_pet_id
    if @photo.save
      redirect_to album_path @pet_id, @album_id
    else
      render :new
    end
  end

  def show
    @photo = set_photo
    @album_id = set_album_id
    @pet_id = set_pet_id
    @pet = Pet.where(id: @pet_id)

  end

  def edit
    @photo = set_photo
  end

  def update
    @photo = set_photo
    @album_id = set_album_id
    @pet_id = set_pet_id
    if @photo.update_attributes(photo_params)
      redirect_to photo_path @pet_id, @album_id, @photo.id
    else
      render :edit
    end
  end

  def delete
    @photo = set_photo
    @album_id = set_album_id
    @pet_id = set_pet_id
    @photo.destroy
    redirect_to album_path @pet_id, @album_id
  end

  private

  def set_photo
    Photo.find(params[:id])
  end

  def set_album_id
    params[:album_id]
  end

  def set_pet_id
    params[:pet_id]
  end

  def photo_params
  	params.require(:photo).permit(:description, :album_id, :avatar, :remote_avatar_url)
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/edit.html.erb
<%= form_for(@photo, url: update_photo_path) do |f| %>

  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form_box form-horizontal">
    <h1>Edit Photo</h1>
    <div class="form-group first">
      <%= f.label "Description", class:"col-md-3 lower"%>
      <div class="col-md-9">      
        <%= f.text_field :description, class:"form-control", autofocus: true, autocomplete: "off" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "Upload File", class:"col-md-3 lower"%>
      <div class="col-md-9">      
        <%= f.file_field :avatar, class:"form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "or image URL", class:"col-md-3 lower"%>
      <div class="col-md-9">      
        <%= f.text_field :remote_avatar_url, class:"form-control", placeholder: "Image URL", autocomplete: "off" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: "button"%>
  </div>

<% end %>

app/views/photos/main.html.erb
<div class="container-fluid box">
	<h1>Photos</h1>
	<div class="pet spacer"><%= link_to "Create Photo", new_photo_path(@album_id) %></div>
	<div class="row last">
		<% @photos.each do |photo| %>			
			<div class="col-xs-4 col-sm-4 col-md-4 pet">
				<%= link_to photo.description, photo_path(photo.id) %>
			</div>
		<% end %>
	</div>
</div>

app/views/photos/new.html.erb
<%= form_for @photo, :url => create_photo_path do |f| %>

  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_box form-horizontal">
    <h1>New Photo</h1>
    <div class="form-group first">
      <%= f.label "Description", class:"col-md-3 lower"%>
      <div class="col-md-9">      
        <%= f.text_field :description, class:"form-control", placeholder: "Description", autofocus: true, autocomplete: "off" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "Upload File", class:"col-md-3 lower"%>
      <div class="col-md-9">      
        <%= f.file_field :avatar, class:"form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "or image URL", class:"col-md-3 lower"%>
      <div class="col-md-9">      
        <%= f.text_field :remote_avatar_url, class:"form-control", placeholder: "Image URL", autocomplete: "off" %>
      </div>
    </div>
    <!-- hidden field to add relationship between photo and current album -->
    <%= f.hidden_field :album_id, :value => @album_id %>

    <div class="form-group">
      <%= f.submit "Save", class: "button"%>
  </div>

<% end %>

  

app/views/photos/show.html.erb
<div class="container-fluid box">
	<header>
		<p class="larger"><%= @photo.description %></p>
	</header>
	<div class="pet last">
		<% if @pet[0].user_id == current_user.id %>
			<%= link_to "Edit", edit_photo_path(@pet_id, @album_id, @photo.id) %> &nbsp;&nbsp;
			<%= link_to "Delete", photo_path(@pet_id, @album_id, @photo.id), :method => :delete %><br>
		<% end %>
		<%= link_to "Back to #{@photo.album.title} Album Page" , album_path(@pet_id, @photo.album_id) %><br>
		<%= image_tag @photo.avatar_url.to_s %>
	</div>
</div>