config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'users#main'

  get 'users' => 'users#main'
  
  post 'pets/:id' => 'users#follow', as: :follow
  
  #####
  #PETS
  #####
  get 'pets' => 'pets#main'
  #create profile
  get 'pets/new' => 'pets#new', as: :new_pet #retrieve form
  post 'pets' => 'pets#create' #post
  #display profile
  get 'pets/:id' => 'pets#show', as: :pet
  #edit profile
  get 'pets/:id/edit' => 'pets#edit', as: :edit_pet
  patch 'pets/:id' => 'pets#update', as: :update_pet
  #delete profile
  delete 'pets/:id' => 'pets#delete'

  #######
  #ALBUMS
  #######
  get 'pets/:pet_id/albums' => 'albums#main', as: :albums

  get 'pets/:pet_id/albums/new' => 'albums#new', as: :new_album
  post 'pets/:pet_id/albums' => 'albums#create', as: :create_album

  get 'pets/:pet_id/albums/:id' => 'albums#show', as: :album

  get 'pets/:pet_id/albums/:id/edit' => 'albums#edit', as: :edit_album
  patch 'pets/:pet_id/albums/:id' => 'albums#update', as: :update_album

  delete 'pets/:pet_id/albums/:id' => 'albums#delete'

  #######
  #PHOTOS
  #######
  get 'pets/:pet_id/albums/:album_id/photos/' => 'photos#main', as: :photos

  get 'pets/:pet_id/albums/:album_id/photos/new' => 'photos#new', as: :new_photo
  post 'pets/:pet_id/albums/:album_id/photos' => 'photos#create', as: :create_photo

  get 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#show', as: :photo

  get 'pets/:pet_id/albums/:album_id/photos/:id/edit' => 'photos#edit', as: :edit_photo
  patch 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#update', as: :update_photo

  delete 'pets/:pet_id/albums/:album_id/photos/:id' => 'photos#delete'

  ##########
  #FOLLOWING
  ##########
  post 'pets/:id/follow' => 'pets#follow', as: :follow_pet
  delete 'pets/:id/unfollow' => 'pets#unfollow', as: :unfollow_pet

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<header>
	<div class="container-fluid header">
		<div class="row navigation">
			<div class="col-xs-5 col-sm-3 col-md-3 logo">
        <%= link_to "Pet Album", users_path %>
      </div>
      <% if user_signed_in? %>
        <div class="col-xs-7 col-sm-9 col-md-9 link">
          <%= render 'search_bar' %> 
          &nbsp; &nbsp;
          <%= link_to "", pets_path, class:"fa fa-user" %>
          &nbsp; &nbsp; &nbsp;
          <%= link_to '', destroy_user_session_path, :method => :delete, class:"fa fa-sign-out" %>
        </div>
      <% else %>
        <div class="col-xs-3 col-sm-2 col-md-2 col-xs-offset-4 col-sm-offset-7 col-md-offset-7 link">
          <%= link_to '', new_user_registration_path, class: "fa fa-user-plus" %>
          &nbsp; &nbsp; &nbsp;
          <%= link_to '', new_user_session_path, class: "fa fa-sign-in" %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/application/_main_header.html.erb
<header>
	<div class="container-fluid">
		<div class="row navigation">
			<div class="col-xs-2 col-sm-2 col-md-2"><h3>PetAlbum</h3></div>
			<div class="col-xs-1 col-sm-1 col-md-1 col-xs-offset-8 col-sm-offset-8 col-md-offset-8 link"><%= link_to "Profile", user_path %></div>
			<div class="col-xs-1 col-sm-1 col-md-1 link"><%= link_to "Edit", edit_user_path %></div>
		</div>
	</div>
</header>

app/views/application/_search_bar.html.erb
<%= form_tag users_path, :method => 'get', id:"search-form" do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Pets", class:"clear" %>
    <a class="fa fa-search merge" aria-hidden="true">
    	<%= submit_tag "", :name => nil, class:"hidden_click" %>
    </a>
<% end %>